### ISSUE TITLE
Collapsible classes causing weird behaivor

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/tocbot#18]
The module seems to be configured to deal with h2, h3, h4, & h5. It seems to be adding the appropriate ID tag to items tagged h4 and h5, but my h4 and h5 items are not showing up in the TOC Block.

![Tocbot___Demo](https://user-images.githubusercontent.com/3144571/70099911-d0a70900-15f5-11ea-8536-103f1a38f621.png)

I checked markup and some headers were properly tagged h4 and had the necessary ID (see screenshot taken from inspector in Chrome).

![DevTools_-_localhost_32815_test-content](https://user-images.githubusercontent.com/3144571/70100156-7a869580-15f6-11ea-8b8b-2808a445000f.png)

Does not show up = in TOC Block. It does show up in body.

**Comment by stpaultim** [comment]
Nevermind. It's not a question of being h2 or h5, it has to do with the order in which they appear. Still not sure of pattern, but if I change the first item to h5, it shows up and some others disappear.

When I talk about showing up or disappearing, I am speaking exclusively about the TOC Block. Everything seems to work fine in body field.

**Comment by stpaultim** [comment]
OK, my problem had to do with the list being collapsible. The default classes in these two fields were causing lots of weird behavior, once I removed these default classes, everything worked as expected. 

![Tocbot___Demo](https://user-images.githubusercontent.com/3144571/70101093-845dc800-15f9-11ea-8342-be1122d2146a.png)

I think I'm testing with a clean backdrop CMS install. I will try again with fresh install. EDIT: Retested on clean Backdrop install and same behavior. Now, with experience it's clearly trying to hide/collapse certain elements and then automatically reveal them during the scroll. But, it's really weird and not helpful. This behavior might be useful if some wants it and is theming for it. But, I think it would be best to start without collapsing on by default. 

Solution, might be to leave these two fields black with a suggested class in help text?

 - - - - - - - - - 

Here are the same blocks with the default classes on initial install of the module. 

![Tocbot___toc](https://user-images.githubusercontent.com/3144571/70102239-1fa46c80-15fd-11ea-94f8-28696fbd458f.png)

**Comment by olafgrabienski** [comment]
Thanks for your feedback @stpaultim. Obviously, the collapsible behaviour can cause confusion! Interestingly, when I discovered and used the D7 module for the first time, it didn't confuse me at all ... maybe it surprised me, but it made a, well, quite natural impression to me. I guess, amongst other factors, the first impression depends on the (test) content. I have for instance a website with a documentation page which contains several long sections, and there the collapsible behavior does a really great job.

Your suggestion to leave the collapsed class blank on installation, is an interesting idea! That would however change the default behavior in comparison to the D7 version and, probably more important: in comparison to the [library demo page](https://tscanlin.github.io/tocbot/). For this reason I'm not sure.

What do you think about the alternative to improve documentation and/or help texts to inform people about the collapsible behavior?

**Comment by stpaultim** [comment]
> What do you think about the alternative to improve documentation and/or help texts to inform people about the collapsible behavior?

Yes, that could be very helpful. I will try to test again today and see if I have more specific ideas. If you are correct about ability to used fixed positioning out of the box, that would be very helpful. 

I was not able to get that to work in a useful way.

**Comment by olafgrabienski** [comment]
Closing in favor of #20. In that issue, I'll include information in the README about the suggested configuration to get started with the module (Toc block in a sidebar fixed when scrolling down, dynamic collapsing behavior).
