### ISSUE TITLE
Better labels + help text for Module settings

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/tocbot#19]
It took me a while to figure this out. Maybe the label should be "Minimum number of headers" with minActivate in help text?

![Tocbot___toc](https://user-images.githubusercontent.com/3144571/70102845-013f7080-15ff-11ea-8dc5-0b3151d3a851.png)

I think I would put a more descriptive label on tocTitle as well. It does not take too long to figure that out, but it's not as obvious as it could be.

**Comment by olafgrabienski** [comment]
Good point! The wording of some *Module* setting labels seems to be inspired by the *JavaScript* related parts further below on the settings page. While the latter reflects the Tocbot API and sounds therefore more 'technical', we should choose more 'human' language in the *Module* settings.

**Comment by olafgrabienski** [comment]
For reference, there are four settings in the *Module* section of the configuration page:

> **Extra Body Class on Activation**
> When the tocbot is activated you can add an extra class to the body to adjust the theme of your site if desired. Leave blank if you dont need this.

> **tocTitle**
> An optional title for the TOC, leave blank for none. Will be an strong tag with class toc-title so you can theme it

> **minActivate (number)**
> Only activate if greater than or equal to this many headings

> **Create Automatic Ids**
> Using Javascript automatic Ids can be created needed for Tocbot to work, or disable it if you have another means of creating ids such as a text filter module

I'll make suggestions for all of them.

**Comment by olafgrabienski** [comment]
Here are my suggestions:

> **Body class**
> Additional body class for pages with a Tocbot block.

> **Toc title**
> A title for the table of contents. Leave blank for none.

> **Minimum number of headings**
> Displays the Tocbot block only on pages where the number of headings is greater than or equal to this value.

> **Create automatic IDs**
> Use JavaScript to create automatic IDs for headings. Disable if you want to create your IDs otherwise, e.g. manually or using a text filter module.

I'm going to file a PR and will merge it right away. (Feel free to reopen the issue. And thanks for your helpful suggestion, @stpaultim!)
