### ISSUE TITLE
Add screenshots /screencast to README

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/tocbot#26]
It would be nice to show a couple of screenshots, or even a screencast, to illustrate how Tocbot looks like and how it works.

**Comment by olafgrabienski** [comment]
As chance would have it, @stpaultim created a video introduction to Tocbot: https://www.youtube.com/watch?v=awh-JYef2i8

@stpaultim As mentioned in Gitter, your video is very helpful! I'd like to add it to the README. What do you think about it?

**Comment by stpaultim** [comment]
@olafgrabienski - Certainly, feel free to link to the video in the README. Also, if you have any suggestions, I could probably redo it sometime in the next few weeks to make it better.

I'm well rehearsed with the part I did already. :-)

I have not experimented much with the other settings on the page, so I did not try to demonstrate them. If there are other settings that you think are worth highlighting, it might be worth taking another try at it.

**Comment by olafgrabienski** [comment]
A few notes how to integrate images in a README:

- Use relative links
  https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes#relative-links-and-image-paths-in-readme-files
- Upload image to an issue and link to it (amongst other suggestions)
  https://stackoverflow.com/questions/10189356/how-to-add-screenshot-to-readmes-in-github-repository
- ~~Upload image to the project's Wiki~~ (not possible, afaik)
- Use a service for absolute URLs
  e.g. https://postimages.org/
- Backdrop-Issue about screenshots for modules and other projects
  https://github.com/backdrop/backdrop-issues/issues/1517

**Comment by olafgrabienski** [comment]
Below are three screenshots. I'll reference them from the Wiki and will link to the Wiki in the README. Will also put a link to Tim's video introduction in the README. Thanks again for your interest in the module, @stpaultim!

No. 1

![backdrop-tocbot-example-01](https://user-images.githubusercontent.com/14188307/71642663-2b905680-2caf-11ea-955f-842e31e83adf.png)

No. 2

![backdrop-tocbot-example-02](https://user-images.githubusercontent.com/14188307/71642664-2b905680-2caf-11ea-833f-b07d2cb8674a.png)

No. 3

![backdrop-tocbot-example-03](https://user-images.githubusercontent.com/14188307/71642665-2c28ed00-2caf-11ea-9953-4917e5d657c7.png)
