### ISSUE TITLE
Problems with collapsed / collapsible settings

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/tocbot#27]
The collapsed and collapsible settings did not work the way I expected. Not sure yet if it's a bug, needs better documentation, or user error on my part. 

![Tocbot___Tocbot](https://user-images.githubusercontent.com/3144571/70363934-06dfc500-1850-11ea-8b7b-d2784b5b1a0d.png)

There are default classes for collapsible `is-collapsible` and isCollapsed `is-collapsed`. These classes are both there by default and the working behavior is that sections are collapsible and collapsed by default.

I expected that by removing either class, I could turn off either of these settings. I expected that by removing `is-collapsible` the TOC would no longer be collapsible and that by removing `is-collapsed` that it would remain collapsible, but not by default. That if I removed both, that the TOC would neither be collapsed or collapsible. 

# **Scenarios**

If I remove `is-collapsible` with both h3 and h4 tags in article/page
RESULT: CSS breaks and it titles end up overlapping and positionFixed does not work(unexpectedly).

![Lorum_Ipsum___Tocbot](https://user-images.githubusercontent.com/3144571/70364774-90dd5d00-1853-11ea-86f7-3ee5a0d36ca4.png)

-----

If I remove `is-collapsed` 
RESULT: It looks good, the TOC is not collapsed by default, but it is also not collapsible, posiltionFixed works correctly. 

![Lorum_Ipsum___Tocbot](https://user-images.githubusercontent.com/3144571/70364399-09dbb500-1852-11ea-85bb-f798a6fc7af4.png)

-----

If I remove `is-collapsed` AND `is-collapsible`
RESULT: It looks good. TOC is neither collapsed or collapsible, but positionFixed no longer works (unexpectedly).

![Lorum_Ipsum___Tocbot](https://user-images.githubusercontent.com/3144571/70364399-09dbb500-1852-11ea-85bb-f798a6fc7af4.png)

---

Closed in favor of this follow-up issue: [Improve configuration form for advanced settings](https://github.com/backdrop-contrib/tocbot/issues/35)

**Comment by olafgrabienski** [comment]
Thanks for your report! Will have a look at it.

Maybe related (copied from #21):

> When I remove `is-collapsed` from the **isCollapsedClass** setting, the space between the CSS classes of a related `<ul>` element is missing. This leads to styling issues (e.g. too much padding).
>
> Actual behavior:
> `toc-listis-collapsible`
> 
> Expected:
> `toc-list  is-collapsible`

**Comment by olafgrabienski** [comment]
@stpaultim - I've had a look at the HTML of your scenarios and noticed what's wrong with it (see below). So far, I don't know the reason for the wrong output. Guess we have to look in the [library's JS file](https://raw.githubusercontent.com/backdrop-contrib/tocbot/1.x-1.x/libraries/tocbot/tocbot.min.js). Do you have some JS skills?

**Removed `is-collapsed`**

Result:
```
<ul class="toc-list ">
  (...)
  <ul class="toc-listis-collapsible">
```

(Note the lacking space between `toc-list` and `is-collapsible`.)

Expected:
```
<ul class="toc-list is-collapsible">
  (...)
  <ul class="toc-list is-collapsible">
```

**Removed `is-collapsible`**

Result:
  `<div class="js-toc-block">`

Expected:
  `<div class="js-toc-block is-position-fixed">`

**Removed `is-collapsed` and `is-collapsible`:**

Result:
  `<div class="js-toc-block">`

Expected:
  `<div class="js-toc-block is-position-fixed">`

**Comment by stpaultim** [comment]
@olafgrabienski - Sorry, my Javascript skills are limited (at this time).

**Comment by olafgrabienski** [comment]
> I expected that by removing either class, I could turn off either of these settings. I expected that by removing `is-collapsible` the TOC would no longer be collapsible and that by removing `is-collapsed` that it would remain collapsible, but not by default. That if I removed both, that the TOC would neither be collapsed or collapsible.

@stpaultim I've talked with a friend with some JS skills about this issue. He said the classes `is-collapsible` and `is-collapsed` are probably not meant to be removed but at best to be changed if people want to use other class names for some reason. (In that case people also need to adapt the CSS to get the out-of-the-box behavior.)

> Not sure yet if it's a bug, needs better documentation, or user error on my part.

While at first sight the issue looked like a bug to me, now I guess it needs better documentation. I'll close this issue and will file a follow-up to improve documentation in the configuration form. Tasks:

- Improve description for the collapsible / collapsed settings.
- Provide a hint to the related setting "collapseDepth".
- Maybe split the form, so that there is a section of advanced settings.

**Comment by olafgrabienski** [comment]
Here's the follow-up issue: #35
