### ISSUE TITLE
Update library version

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/tocbot#49]
I couldn't tell which version of the library was bundled, but it looks like the library is being updated/maintained, so it would be good to update it here (and indicate which version is bundled).

 - https://github.com/tscanlin/tocbot/releases

**Comment by olafgrabienski** [comment]
The bundled version might be [4.8.1](https://github.com/tscanlin/tocbot/releases/tag/v4.8.1), at least it was mentioned as [CDN version](https://github.com/backdrop-contrib/tocbot/commit/a8fe680f4754afa67ec9aea0db12b965d67b2693#diff-c138c02d84619eab7d4d83087907a7383f21a97c19a37038c9e15c7131b2f600R354) when the library was [bundled into the module](https://github.com/backdrop-contrib/tocbot/commit/a8fe680f4754afa67ec9aea0db12b965d67b2693). If I don't miss anything, the library wasn't updated after that.

@laryn There are many changes in the library. I guess I can't evaluate them really. What do you think: is it likely that the library update breaks anything?

**Comment by laryn** [comment]
I don't even see `4.8.1` in the list of releases, and don't see anything called out as a breaking change since then.

**Comment by olafgrabienski** [comment]
> I don't even see 4.8.1 in the list of releases ...

Yep, it wasn't a release, you can see it on this [Tags page](https://github.com/tscanlin/tocbot/tags?after=v4.10.0).

Do you mind providing a pull request?

**Comment by laryn** [comment]
Sure.

**Comment by olafgrabienski** [comment]
Thank you very much! I hope to test the PR one of the next days.

**Comment by olafgrabienski** [comment]
I've applied the PR to a test site. Tocbot works fine, and the appearance of the table of contents didn't change. Works for me!

**Comment by olafgrabienski** [comment]
I've merged the PR by @laryn. Thanks again for providing the PR!
