### ISSUE TITLE
Better placement under "User interface"?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/tocbot#51]
Would this module be better placed under "User interface"?

**Comment by laryn** [comment]
Added a PR in case you agree.

**Comment by olafgrabienski** [comment]
Thanks for the suggestion. I had a look at two sites with Tocbot to get an impression how the module would fit under "User interface", but I couldn't find this item group under "Configuration". Do you have examples of other contributed modules which are placed under "User interface"?

**Comment by laryn** [comment]
- https://github.com/backdrop-contrib/replicate_ui
 - https://github.com/backdrop-contrib/back_to_top
 - https://github.com/backdrop-contrib/jarallax

**Comment by olafgrabienski** [comment]
Thanks for the examples! I agree, Tocbot would get along well with them, especially with Back to Top and Jarallax.

I'll wait some days to give other Tocbot users the opportunity to chime in, e.g. @herbdool and @yorkshire-pudding: What do you think of the placement under "User interface" instead of "Content authoring"?

**Comment by yorkshire-pudding** [comment]
Makes sense to me. I have to say that once setup I rarely go to the config page, but I think this would be a better place for first time users to find it.

**Comment by stpaultim** [comment]
These two modules are under User Interface as well.

https://backdropcms.org/project/stickynav
https://backdropcms.org/project/views_bootstrap

I think it makes sense.

**Comment by olafgrabienski** [comment]
I've just merged the PR. Thanks for your input,  @stpaultim and @yorkshire-pudding! And thanks for the PR, @laryn!
