### ISSUE TITLE
Add a block description

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/tocbot#53]
It might be nice to add a block description if we can think of a nice short one:

![CleanShot 2023-12-15 at 13 40 09@2x](https://github.com/backdrop-contrib/tocbot/assets/871421/11352a37-d8fc-4116-8cef-7cbcba179957)

**Comment by olafgrabienski** [comment]
@laryn Thanks for your suggestion! A block description would be nice, indeed! What do you think of the following descriptions? Do you like a particular one, or do you have other ideas?

- An automatic table of contents (TOC).
- A table of contents (TOC), generated from HTML headings.
- A table of contents (TOC) based on the headings of your content.

**Comment by olafgrabienski** [comment]
Voilà a mockup to see if one of the descriptions from above is short enough:

<img src="https://github.com/backdrop-contrib/tocbot/assets/14188307/9b6ff9f2-99b4-42b6-b8af-911351d0800a" width="609">

---

<img src="https://github.com/backdrop-contrib/tocbot/assets/14188307/12d409a4-42f0-4543-b2c7-7297c4d1470c" width="271">

**Comment by olafgrabienski** [comment]
Coming back to this. @laryn What do you think about the [description text ideas](https://github.com/backdrop-contrib/tocbot/issues/53#issuecomment-1860180359)? As you see in the mockup, even the longer descriptions don't need very much space.

I like the one in the second screenshot:
> A table of contents (TOC) built from your content headings.

Do you have a favorite (or other ideas)?

**Comment by laryn** [comment]
I like that one, too.

**Comment by olafgrabienski** [comment]
@laryn Thanks for your feedback! Are you maybe up to provide a PR? (Or a hint, where and how to add a block description?)

**Comment by laryn** [comment]
@olafgrabienski You can add a ‘description’ entry after the one for ‘info’ here:

https://github.com/backdrop-contrib/tocbot/blob/1.x-1.x/tocbot.module#L32

**Comment by olafgrabienski** [comment]
Thanks for the hint, @laryn! I've added a PR at https://github.com/backdrop-contrib/tocbot/pull/55 and merged it right away.

**Comment by olafgrabienski** [comment]
@laryn Are you interested to address one of the other open issues before I make a new release?

**Comment by laryn** [comment]
@olafgrabienski No, feel free to release, I don't think I'll be working on anything on this module in the near future. 👍
